title: fredgibbs.net
description: Personal and academic website for Fred Gibbs || An experimental playground for digital humanities, digital heritage, critical data, digital mapping, and design.
url: http://fredgibbs.net
safe: true
markdown: kramdown
environment: production
plugins:
  - jekyll-sitemap